backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  # - name: "blog"
  #   label: "Blog"
  #   folder: "src/pages/blog"
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
  #     - {label: "Path", name: "path", widget: "string"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Description", name: "description", widget: "text"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  - name: "company" 
    label: "Companies"
    folder: "src/pages/companies"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "company-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Company Name", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Website URL", name: "website", widget: "string", default: "#"}
      - {label: "Social Media URL",name: "socialMedia", widget: "list",required: false, fields: [{label: Type, name: media, widget: select, options: ["Twitter", "Facebook", "Instagram", "LinkedIn"]}, {label: Url, name: url, widget: string}] }
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Jobs", name: "jobs", widget: "list",required: false, fields: [{label: Job Posted, name: date, widget: datetime}, {label: Position, name: position, widget: string}, {label: Location, name: location, widget: string}, {label: Description, name: description, widget: text}] }
  
  - name: "jobs"
    label: "Jobs"
    folder: "src/pages/jobs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "jobs-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime",}
      - {label: Position, name: position, widget: string}
      - {label: Location, name: location, widget: string}
      - {label: Description, name: description, widget: text}
      - {label: "Company", name: "companyRelated", widget: "relation", collection: "company", searchFields: ["title", display:["title"]], valueField: "title"}

  # - name: "pages"
  #   label: "Pages"
  #   files:
  #     - file: "src/pages/about/about.md"
  #       label: "About"
  #       name: "about"
  #       fields:
  #         - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
  #         - {label: "Path", name: "path", widget: "hidden", default: "/about"}
  #         - {label: "Title", name: "title", widget: "string"}
  #         - {label: "Body", name: "body", widget: "markdown"}
  #     - file: "src/pages/product/product.md"
  #       label: "Products Page"
  #       name: "products"
  #       fields:
  #         - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
  #         - {label: "Path", name: "path", widget: "hidden", default: "/products"}
  #         - {label: Title, name: title, widget: string}
  #         - {label: Image, name: image, widget: image}
  #         - {label: Heading, name: heading, widget: string}
  #         - {label: Description, name: description, widget: string}
  #         - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
  #         - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
  #         - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
  #         - {label: Full_image, name: full_image, widget: image}
  #         - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
