backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  # - name: "blog"
  #   label: "Blog"
  #   folder: "src/pages/blog"
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
  #     - {label: "Path", name: "path", widget: "string"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Description", name: "description", widget: "text"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  - name: "company" 
    label: "Companies"
    folder: "src/pages/companies"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "company-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Company Name", name: "title", widget: "string"}
      - {label: Location, name: location, widget: string}
      - {label: "Website URL", name: "website", widget: "string", default: "#"}
      - {label: "Social Media URL",name: "socialMedia", widget: "list",required: false, fields: [{label: Type, name: media, widget: select, options: ["Twitter", "Facebook", "Instagram", "LinkedIn"]}, {label: Url, name: url, widget: string}] }
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "text", required: false}
  
  - name: "jobs"
    label: "Jobs"
    folder: "src/pages/jobs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: Job Title, name: title, widget: string}
      - {label: Position, name: position, widget: string}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "jobs-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: Description, name: body, widget: markdown}
      - {label: "Company", name: "companyRelated", widget: "relation", collection: "company", searchFields: ["title"], display:["title"], valueField: "path"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/company/company-list.md"
        label: "Companies"
        name: "companyList"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "companies-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/companies"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
      - file: "src/pages/jobsList/jobs.md"
        label: "Jobs"
        name: "jobList"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "jobs-list-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/jobs-list"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
      - file: "src/pages/jobsList/apply.md"
        label: "Apply Job"
        name: "apply"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "job-apply-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/apply"}
          - {label: Title, name: title, widget: string}